completed javascript-loops exercise - Colin Macrae
colin-macrae/c0123-code-solutions pull request #33
Opened 2023-02-02 03:40 UTC by colin-macrae

![346546576743657](https://user-images.githubusercontent.com/122063836/216225921-a2396054-e355-437c-8f84-157414e25bc3.PNG)

2023-02-02 17:17 UTC, shawnkost requested changes
A couple changes Colin!

2023-02-02 17:17 UTC, shawnkost commented on javascript-loops/main.js
> +// function doubleAll(numbers) {
This function shouldn't be commented out!

2023-02-02 17:17 UTC, shawnkost commented on javascript-loops/main.js
> +    keys.push([property]);
This should just be `keys.push(property)` without the brackets

2023-02-03 17:02 UTC, JenBowman1 approved these changes
👍

2023-02-03 17:24 UTC, merged