completed es6-destructuring exercise - Colin Macrae
colin-macrae/c0123-code-solutions pull request #67
Opened 2023-03-13 21:21 UTC by colin-macrae

![3145657434](https://user-images.githubusercontent.com/122063836/224835232-e2270ca8-38ab-4bb8-8120-d994edd3ee7c.PNG)

2023-03-13 23:00 UTC, RobertGardner requested changes

2023-03-13 23:48 UTC, colin-macrae commented
![image](https://user-images.githubusercontent.com/122063836/224856653-61603f52-d1fc-4364-ae3d-f5b128bad9dc.png)

2023-03-13 23:49 UTC, RobertGardner requested changes

2023-03-13 23:49 UTC, RobertGardner commented on es6-destructuring/index.html
>      const book6 = library[3];
This one, too.

2023-03-13 23:56 UTC, colin-macrae commented on es6-destructuring/index.html
>      const book6 = library[3];
Sorry I missed that one.

2023-03-14 13:21 UTC, RobertGardner approved these changes

2023-03-14 16:07 UTC, merged